sync_ca:
  description: "Synchronisiere CA und CRL zum Nginx Proxy Manager per SSH"
  fields:
    npm_host:
      description: "IP oder Hostname von NPM"
      example: "192.168.1.10"
    user:
      description: "SSH-User"
      example: "user"
    password:
      description: "SSH-Passwort"
      example: "supersecure"
    remote_path:
      description: "Zielordner auf dem NPM-Host"
      example: "/data/ssl"
